source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NPLumen_Example', :exclusive => true do
  pod "NPLumen", :path => "../"
end

target 'NPLumen_Tests', :exclusive => true do
  pod "NPLumen", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
